# Generated by Django 5.0.7 on 2024-09-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descuento', models.IntegerField()),
                ('vecesUso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_CategoriasCamisetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgCamisetasVintage/')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('precio', models.FloatField()),
                ('id_Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.marca')),
                ('id_Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.size')),
                ('id_SubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Model_shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.model_client')),
                ('id_Teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.teams')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgCamisetasVintage/')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='VistaAdmin.teams')),
            ],
        ),
    ]
