# Generated by Django 5.0.7 on 2024-08-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_CategoriasCamisetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgCamisetasVintage')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('precio', models.FloatField()),
                ('id_Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.size')),
                ('id_SubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VistaAdmin.subcategoria')),
            ],
        ),
    ]
