# Generated by Django 5.0.7 on 2024-09-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VistaAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_shopping_cart',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
